<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<div class="container text-center">
    <h1 class="mt-5">Finish installation</h1>

    <form class="col-lg-6 offset-lg-3 text-left" action="/big-commerce/update" method="post">
        <div class="form-group">
            <label for="trigger_api_key" class="col-form-label">Trigger Api Key</label>
            <div>
                <input type="text" class="form-control" id="trigger_api_key" name="trigger_api_key">
            </div>
        </div>
        <div class="form-group">
            <label for="public_api_key" class="col-form-label">Public Api Key</label>
            <div>
                <input type="text" class="form-control" id="public_api_key" name="public_api_key">
            </div>
        </div>
        <div class="form-group row">
            <div class="col-md-8">
                <label for="abandoned_period" class="col-form-label">Abandoned period</label>
                <div>
                    <input type="number" value="23" class="form-control" id="abandoned_period" name="abandoned_period">
                </div>
            </div>

            <div class="col-md-4">
                <label for="period_unit" class="col-form-label">State</label>
                <div>
                    <select name="abandoned_unit" class="custom-select" id="period_unit">
                        <option value="seconds">Seconds</option>
                        <option value="minutes">Minutes</option>
                        <option selected value="hours">Hours</option>
                        <option value="days">Days</option>
                    </select>
                </div>
            </div>
        </div>
        <input type="hidden" name="store_hash" value="asdss">
        <button type="submit" class="btn btn-primary col-sm-12">Finish</button>
    </form>
</div>