<?php
declare(strict_types=1);
/**
 * @var \Src\Core\Domain\Model\Auth\Integration $integration
 */
?>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<?php if (!empty($integration->getTriggerApiKey())) { ?>
    <div class="container text-center">
        <h1 class="mt-5 mb-5">The application is installed and configured. Api Key: <kbd><?php echo $integration->getApiKey() ?></kbd></h1>
        <span class="text-success" style="font-size: 350px;">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              <path fill-rule="evenodd"
                    d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
            </svg>
        </span>
    </div>
<?php } else { ?>
    <div class="container text-center">
        <h1 class="mt-5 mb-5">Insert Trigger Api Key from ManyChat</h1>

        <form class="col-lg-6 offset-lg-3" action="/big-commerce/update" method="post">
            <div class="row justify-content-center">
                <div class="form-group mx-sm-3 mb-2">
                    <input type="text" name="trigger_api_key" class="form-control" placeholder="Trigger Api Key">
                </div>
                <input type="hidden" name="store_hash" value="<?php echo $integration->getStoreHash()->getHash() ?>">
                <button type="submit" class="btn btn-primary mb-2">Link accounts</button>
            </div>
        </form>
    </div>
<?php } ?>