<?php
declare(strict_types=1);
/**
 * @var \Src\Core\Domain\Model\Auth\Integration $integration
 */
?>

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">

<?php if (!empty($integration->getTriggerApiKey())) { ?>
    <div class="container text-center">
        <h1 class="mt-5 mb-5">The application is installed and configured</h1>
        <span class="text-success" style="font-size: 350px;">
            <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-check-circle" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
              <path fill-rule="evenodd" d="M8 15A7 7 0 1 0 8 1a7 7 0 0 0 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
              <path fill-rule="evenodd"
                    d="M10.97 4.97a.75.75 0 0 1 1.071 1.05l-3.992 4.99a.75.75 0 0 1-1.08.02L4.324 8.384a.75.75 0 1 1 1.06-1.06l2.094 2.093 3.473-4.425a.236.236 0 0 1 .02-.022z"/>
            </svg>
        </span>
    </div>
<?php } else { ?>
    <div class="container text-center">
        <h1 class="mt-5">Finish installation</h1>

        <form class="col-lg-6 offset-lg-3 text-left" action="/big-commerce/update" method="post">
            <div class="form-group">
                <label for="trigger_api_key" class="col-form-label">Trigger Api Key</label>
                <div>
                    <input type="text" class="form-control" id="trigger_api_key" name="trigger_api_key">
                </div>
            </div>
            <div class="form-group">
                <label for="public_api_key" class="col-form-label">Public Api Key</label>
                <div>
                    <input type="text" class="form-control" id="public_api_key" name="public_api_key">
                </div>
            </div>
            <div class="form-group row">
                <div class="col-md-8">
                    <label for="abandoned_period" class="col-form-label">Abandoned period</label>
                    <div>
                        <input type="text" value="23" class="form-control" id="abandoned_period" name="abandoned_period">
                    </div>
                </div>

                <div class="col-md-4">
                    <label for="period_unit" class="col-form-label">State</label>
                    <div>
                        <select name="abandoned_unit" class="custom-select" id="period_unit">
                            <option value="seconds">Seconds</option>
                            <option value="minutes">Minutes</option>
                            <option selected value="hours">Hours</option>
                            <option value="days">Days</option>
                        </select>
                    </div>
                </div>
            </div>
            <input type="hidden" name="store_hash" value="<?php echo $integration->getStoreHash()->getHash() ?>">
            <button type="submit" class="btn btn-primary col-sm-12">Finish</button>
        </form>
    </div>
<?php } ?>