### Home page
GET https://127.0.0.1
Content-Type: application/json

### Auth
GET https://127.0.0.1/big-commerce/auth?code=test-code&context=test-context&scope=test-scope
Content-Type: application/json

### Load
GET https://127.0.0.1/big-commerce/load
Content-Type: application/json

### Load
POST https://127.0.0.1/big-commerce/webhook/receive
Content-Type: application/json

{
  "created_at": 1600013349,
  "store_id": "1001380158",
  "producer": "stores/t69qaobe3e",
  "scope": "store/cart/lineItem/updated",
  "hash": "8057e97b2cb64a4d80d2651513bb061366a75440",
  "data": {
    "type": "cart_line_item",
    "id": "4e273710-b26a-441d-b2aa-2874789d4b22",
    "cartId": "95a9231a-3ef7-4ccd-bbc7-f3e21cd6c842"
  }
}

###
GET https://127.0.0.1/big-commerce/jobs
Content-Type: application/json